### ISSUE TITLE
User Journey

### ISSUE THREAD

**Issue by veredrec** [facn2/path-18#6]
### As a user I can browse a variety of career paths and view detailed information about the ones that I am interested in.

**User Stories:**
As a user I can:

- [ ] read welcome page and instructions on how to use the app
- [ ] view card with job and decide if I like / dislike it
- [ ] click on card to view more details
- [ ] View list of jobs I like
- [ ] click on job to view details on the job and career path
- [ ] read details instructions for the app in the help page
